### ISSUE TITLE
Record Admin에서 start_at, end_at 수정이 불가능해짐

### ISSUE THREAD

**Issue by UkiDelly** [ormi3-2-4/Backend#26]
어드민 페이지에서 Record을 생성/수정 하려고 할때 `start_at`, `end_at` 필드가 수정 불가능 한 필드라는 오류가 발생

두 필드를 모두 `read_only`로 설정하면 문제는 없음

![screenshot_2023 12 21_11-53_AM](https://github.com/ormi3-2-4/Backend/assets/60603701/1ac83bdb-d085-43ed-b841-b49acfa4ca8b)

**Comment by jmp7911** [comment]
- auto_now_add=True auto_now=True 로 주면 editable=False, Blank=True 가 기본값으로 된다고 합니다

editable=True, Blank=True 를 모델에 명시해도 안되네요
